# Use the official Golang image as a builder
FROM golang:1.22.4-alpine
RUN apk add build-base
WORKDIR /app

COPY . .

ENV CGO_ENABLED=1

RUN go mod tidy

RUN go build -o main ./cmd/main.go

EXPOSE 8080

CMD ["./main"]
